import { Mountain, Waves, Landmark, TreePine, Compass, Footprints, ShieldCheck } from "lucide-react";

export type Activity = {
  id: number;
  name: string;
  city: string;
  type: "desert" | "hiking" | "water" | "cultural" | "guided";
  duration: string;
  price: number;
  groupPrice: number;
  rating: number;
  reviews: number;
  difficulty: string;
  phone: string;
  description: string;
  image: string;
  icon?: any;
  highlights?: string[];
};

export const activities: Activity[] = [
  // --- DÉSERT & SAHARA ---
  {
    id: 1,
    name: "Ski sur sable à la Grande Dune de Taghit",
    city: "Taghit",
    type: "desert",
    duration: "Demi-journée",
    price: 3500,
    groupPrice: 2800,
    rating: 4.9,
    reviews: 215,
    difficulty: "Modéré",
    phone: "+213 49 81 23 45",
    description: "Glissez sur le sable doré de la gigantesque dune de Taghit, l'une des plus spectaculaires au monde face au ksar millénaire.",
    image: "/images/activities/activities_1_ski_sur_sur_sable_taghit_059_jpg.webp",
    highlights: ["Grande dune de Taghit", "Planche fournie", "Moniteur expérimenté", "Coucher de soleil féerique"],
  },
  {
    id: 2,
    name: "Trek chamelière & Bivouac sous les étoiles",
    city: "Djanet",
    type: "desert",
    duration: "2 jours",
    price: 12500,
    groupPrice: 9800,
    rating: 4.9,
    reviews: 180,
    difficulty: "Facile",
    phone: "+213 29 35 67 89",
    description: "Caravane traditionnelle à dos de dromadaire dans les dunes de l'Erg Admer. Nuit en tente nomade et cuisine sur la braise.",
    image: "/images/activities/activities_2_le_chameau_et_la_grande_dune_croppe.webp",
    highlights: ["Erg Admer", "Nuit sous la Voie Lactée", "Thé à la menthe touareg", "Taguella traditionnelle"],
  },
  {
    id: 3,
    name: "Lever de soleil à l'Assekrem & Monts du Hoggar",
    city: "Tamanrasset",
    type: "desert",
    duration: "3 jours",
    price: 18500,
    groupPrice: 15000,
    rating: 4.9,
    reviews: 142,
    difficulty: "Sportif",
    phone: "+213 29 34 56 78",
    description: "Ascension mythique vers le plateau de l'Assekrem à 2700m d'altitude pour admirer l'un des plus beaux levers de soleil de la planète.",
    image: "/images/activities/activities_18_glecoquierre-hoggar2009-assekrem_gd.webp",
    highlights: ["Altitude 2728m", "Ermitage Charles de Foucauld", "Paysages volcaniques lunaires", "Pistes en 4x4"],
  },
  {
    id: 4,
    name: "Traversée du Grand Erg Occidental en 4x4",
    city: "Timimoun",
    type: "desert",
    duration: "Journée entière",
    price: 7500,
    groupPrice: 6000,
    rating: 4.8,
    reviews: 128,
    difficulty: "Modéré",
    phone: "+213 49 90 12 34",
    description: "Franchissement des crêtes de dunes rouges de Timimoun, visite des foggaras historiques et arrêt à la grotte d'Ighzer.",
    image: "/images/activities/activities_19_algerian_desert_where_the_beautiful.webp",
    highlights: ["Dunes rouges du Gourara", "Visite des foggaras UNESCO", "Grotte d'Ighzer", "Pique-nique saharien"],
  },
  {
    id: 5,
    name: "Trek de Séfar & Fresques Rupestres (UNESCO)",
    city: "Djanet",
    type: "hiking",
    duration: "4 jours",
    price: 24000,
    groupPrice: 19500,
    rating: 5.0,
    reviews: 95,
    difficulty: "Sportif",
    phone: "+213 29 47 55 66",
    description: "Expédition dans la cité de pierre de Séfar, la plus grande ville troglodytique au monde abritant des milliers de peintures néolithiques.",
    image: "/images/activities/activities_20_central_algeria_esa343516_jpg.webp",
    highlights: ["Site UNESCO n°1", "Fresques des dieux martiens", "Canyon de pierre", "Guide touareg assermenté"],
  },

  // --- RANDONNÉE & MONTAGNE ---
  {
    id: 6,
    name: "Ascension du Djurdjura & Lac Agulmin",
    city: "Tikjda",
    type: "hiking",
    duration: "Journée entière",
    price: 3200,
    groupPrice: 2500,
    rating: 4.8,
    reviews: 165,
    difficulty: "Modéré",
    phone: "+213 26 89 12 34",
    description: "Sentier grandiose à travers la forêt de cèdres de l'Atlas menant au lac glaciaire d'Agulmin à plus de 1700 mètres d'altitude.",
    image: "/images/activities/activities_4_heights_of_tikjda_road_to_agulmin_l.webp",
    highlights: ["Lac d'altitude Agulmin", "Forêt de cèdres millénaires", "Panorama Grande Kabylie", "Air pur montagnard"],
  },
  {
    id: 7,
    name: "Randonnée du Parc National du Djurdjura",
    city: "Tizi Ouzou",
    type: "hiking",
    duration: "Journée entière",
    price: 3000,
    groupPrice: 2400,
    rating: 4.7,
    reviews: 130,
    difficulty: "Modéré",
    phone: "+213 26 21 34 56",
    description: "Découvrez les villages berbères perchés, les falaises calcaires de la main du juif et la faune protégée du parc.",
    image: "/images/activities/activities_3_djurdjura_national_park_algeria_jpg.webp",
    highlights: ["Villages kabyles authentiques", "Falaises calcaires", "Faune alpine", "Déjeuner du terroir"],
  },
  {
    id: 8,
    name: "Sentier du Cap Carbon & Pic des Singes",
    city: "Béjaïa",
    type: "hiking",
    duration: "Demi-journée",
    price: 2200,
    groupPrice: 1800,
    rating: 4.8,
    reviews: 190,
    difficulty: "Facile",
    phone: "+213 34 21 56 78",
    description: "Balade panoramique le long du phare le plus haut de Méditerranée au Cap Carbon, à la rencontre des macaques de Barbarie sauvages.",
    image: "/images/activities/activities_5_forest_of_akfadou_jpg.webp",
    highlights: ["Phare du Cap Carbon", "Macaques de Barbarie", "Vue mer à 360°", "Sentier boisé d'oliviers"],
  },
  {
    id: 9,
    name: "Trek des Canyons du Ghoufi & Balcon des Aurès",
    city: "Batna",
    type: "hiking",
    duration: "Journée entière",
    price: 3500,
    groupPrice: 2800,
    rating: 4.9,
    reviews: 155,
    difficulty: "Modéré",
    phone: "+213 33 81 22 47",
    description: "Explorez le 'Grand Canyon algérien' du Ghoufi avec ses maisons troglodytes en gradins sculptées dans la falaise au-dessus de l'oasis.",
    image: "/images/destinations/destinations_60_gorges_d_el_kantara_biskra01_jpg.webp",
    highlights: ["Canyons spectaculaires", "Maisons troglodytes chaouies", "Palmeraie en contrebas", "Histoire des Aurès"],
  },
  {
    id: 10,
    name: "Forêt des Cèdres de Theniet El Had",
    city: "Tissemsilt",
    type: "hiking",
    duration: "Journée entière",
    price: 2500,
    groupPrice: 2000,
    rating: 4.6,
    reviews: 95,
    difficulty: "Facile",
    phone: "+213 46 55 67 89",
    description: "Randonnée vivifiante dans le premier parc national algérien au milieu de cèdres géants vieux de plusieurs siècles.",
    image: "/images/activities/activities_7_parc_national_de_theniet_el_had2_jp.webp",
    highlights: ["Cèdres tricenténaires", "Sources naturelles", "Climat frais", "Idéal en famille"],
  },

  // --- MER & ACTIVITÉS NAUTIQUES ---
  {
    id: 11,
    name: "Plongée & Exploration des Grottes Merveilleuses",
    city: "Jijel",
    type: "water",
    duration: "Journée entière",
    price: 4500,
    groupPrice: 3800,
    rating: 4.8,
    reviews: 175,
    difficulty: "Facile",
    phone: "+213 34 47 89 12",
    description: "Naviguez en bateau le long de la Corniche de Jijel et plongez dans les eaux turquoise des grottes sous-marines préservées.",
    image: "/images/activities/activities_9_the_paradise_beach_02_jpg.webp",
    highlights: ["Grottes marines", "Eaux translucides", "Baptême de plongée", "Matériel complet fourni"],
  },
  {
    id: 12,
    name: "Excursion en voilier aux Îles Habibas",
    city: "Oran",
    type: "water",
    duration: "Journée entière",
    price: 6500,
    groupPrice: 5200,
    rating: 4.9,
    reviews: 140,
    difficulty: "Facile",
    phone: "+213 41 40 88 00",
    description: "Sortie en mer vers la réserve naturelle marine protégée des Îles Habibas. Snorkeling parmi les dauphins et coraux méditerranéens.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop&q=80",
    highlights: ["Réserve marine protégée", "Observation des dauphins", "Baignade en eau cristalline", "Déjeuner marin à bord"],
  },
  {
    id: 13,
    name: "Kayak de mer aux falaises de Séraïdi",
    city: "Annaba",
    type: "water",
    duration: "Demi-journée",
    price: 3000,
    groupPrice: 2400,
    rating: 4.7,
    reviews: 110,
    difficulty: "Modéré",
    phone: "+213 38 87 12 34",
    description: "Pagaie le long des falaises côtières du massif de l'Édough, criques inaccessibles à pied et plages secrètes.",
    image: "/images/activities/activities_11_20181114_145348_hdrseraidi_beach_jp.webp",
    highlights: ["Criques sauvages secrètes", "Kayak double ou solo", "Moniteur diplômé", "Snorkeling inclus"],
  },
  {
    id: 14,
    name: "Baignade & Détente à la Plage Chenoua",
    city: "Tipaza",
    type: "water",
    duration: "Journée entière",
    price: 1800,
    groupPrice: 1500,
    rating: 4.6,
    reviews: 145,
    difficulty: "Facile",
    phone: "+213 24 43 23 45",
    description: "Profitez des eaux turquoise de la baie abritée de Chenoua, avec transats, paddle et restaurant les pieds dans l'eau.",
    image: "/home-page-pic/tipaza.jpg",
    highlights: ["Plage de sable doré", "Paddle & canoë", "Cadre verdoyant", "Proche du port antique"],
  },

  // --- CULTURE & PATRIMOINE ---
  {
    id: 15,
    name: "Visite guidée de la Casbah d'Alger (UNESCO)",
    city: "Alger",
    type: "cultural",
    duration: "Demi-journée",
    price: 2500,
    groupPrice: 2000,
    rating: 4.9,
    reviews: 320,
    difficulty: "Facile",
    phone: "+213 21 73 45 67",
    description: "Arpentez les ruelles en escalier de la mythique Casbah avec un guide historien local. Palais ottomans, ateliers d'ébénisterie et thé sur terrasse panoramique.",
    image: "https://images.unsplash.com/photo-1549294413-26f195200c16?w=1200&h=800&fit=crop&q=80",
    highlights: ["Palais Dar Mustapha Pacha", "Terrasse avec vue sur la baie", "Artisans traditionnels", "Guide historien agréé"],
  },
  {
    id: 16,
    name: "Circuit des Ponts Suspendus & Palais Ahmed Bey",
    city: "Constantine",
    type: "cultural",
    duration: "Demi-journée",
    price: 2500,
    groupPrice: 2000,
    rating: 4.9,
    reviews: 280,
    difficulty: "Facile",
    phone: "+213 31 92 64 64",
    description: "Traversez le spectaculaire pont Sidi M'Cid suspendu au-dessus des gorges du Rhummel et explorez les patios féeriques du Palais du Bey.",
    image: "/home-page-pic/Constantine 🇩🇿.jpg",
    highlights: ["Pont suspendu Sidi M'Cid", "Palais Ahmed Bey ottoman", "Musée national Cirta", "Panorama vertigineux"],
  },
  {
    id: 17,
    name: "Visite archéologique de Timgad (UNESCO)",
    city: "Batna",
    type: "cultural",
    duration: "Demi-journée",
    price: 2800,
    groupPrice: 2200,
    rating: 4.9,
    reviews: 245,
    difficulty: "Facile",
    phone: "+213 33 81 67 89",
    description: "Plongez dans la 'Pompéi de l'Afrique', cité romaine parfaitement conservée avec son arc de Trajan, son théâtre antique et ses thermes.",
    image: "/images/activities/activities_15_timgad_ruinas_batna_jpg.webp",
    highlights: ["Arc de Trajan intact", "Théâtre romain de 3500 places", "Musée des mosaïques", "Patrimoine mondial UNESCO"],
  },
  {
    id: 18,
    name: "Ruines Romaines & Tombeau de la Chrétienne",
    city: "Tipaza",
    type: "cultural",
    duration: "Demi-journée",
    price: 2200,
    groupPrice: 1800,
    rating: 4.8,
    reviews: 230,
    difficulty: "Facile",
    phone: "+213 24 43 23 45",
    description: "Promenade poétique entre pins parasols et mer bleue au milieu des basiliques romaines célébrées par Albert Camus, suivie du mausolée royal de Maurétanie.",
    image: "/images/activities/activities_14_alg_rie_tipaza_01_jpg.webp",
    highlights: ["Parc archéologique marin", "Stèle Albert Camus", "Mausolée royal de Maurétanie", "Guide conférencier"],
  },
  {
    id: 19,
    name: "Cité Romaine de Cuicul / Djémila (UNESCO)",
    city: "Sétif",
    type: "cultural",
    duration: "Demi-journée",
    price: 2500,
    groupPrice: 2000,
    rating: 4.8,
    reviews: 160,
    difficulty: "Facile",
    phone: "+213 36 66 78 90",
    description: "Visite de l'une des merveilles de l'architecture romaine en montagne, dotée d'un musée abritant certaines des plus belles mosaïques au monde.",
    image: "/images/activities/activities_16_malysian_tourist_in_djmila_jpg.webp",
    highlights: ["Mosaïques mondialement célèbres", "Arc de Caracalla", "Forum romain préservé", "Site montagneux grandiose"],
  },
  {
    id: 20,
    name: "Art & Palais Islamiques de Tlemcen",
    city: "Tlemcen",
    type: "cultural",
    duration: "Journée entière",
    price: 3000,
    groupPrice: 2400,
    rating: 4.8,
    reviews: 195,
    difficulty: "Facile",
    phone: "+213 43 27 71 20",
    description: "Voyage au cœur de la perle du Maghreb : Palais Royal El Mechouar, Mosquée de Mansourah et sanctuaire de Sidi Boumédiène.",
    image: "/home-page-pic/el-machouar.jpg",
    highlights: ["Palais Royal El Mechouar", "Minaret de Mansourah", "Sanctuaire Sidi Boumédiène", "Art hispano-mauresque"],
  },
  {
    id: 21,
    name: "Immersion dans les Ksour de la Vallée du M'Zab",
    city: "Ghardaïa",
    type: "cultural",
    duration: "Journée entière",
    price: 3500,
    groupPrice: 2800,
    rating: 5.0,
    reviews: 210,
    difficulty: "Facile",
    phone: "+213 29 88 41 12",
    description: "Guidé par les sages de la cité sainte de Beni Isguen, découvrez les règles d'urbanisme ancestrales et l'architecture organique qui inspira Le Corbusier.",
    image: "/images/destinations/destinations_13_ksar_ghardaia_place_march_1_jpg.webp",
    highlights: ["Ksar sacré de Beni Isguen", "Marché à la criée historique", "Système de partage des eaux", "Classé UNESCO"],
  },
];

export const activityCities = [
  "All",
  "Alger",
  "Oran",
  "Constantine",
  "Tlemcen",
  "Annaba",
  "Béjaïa",
  "Tipaza",
  "Ghardaïa",
  "Djanet",
  "Tamanrasset",
  "Taghit",
  "Timimoun",
  "Batna",
  "Tikjda",
  "Jijel",
  "Sétif",
  "Tizi Ouzou",
];

export const activityTypes = [
  { id: "all", label: "Toutes" },
  { id: "desert", label: "Désert & Sahara" },
  { id: "hiking", label: "Randonnée & Montagne" },
  { id: "cultural", label: "Culture & Histoire" },
  { id: "water", label: "Mer & Nautique" },
];
