export type Vehicle = {
  id: number;
  name: string;
  type: string;
  agency: string;
  city: string;
  rating: number;
  reviews: number;
  price: number;
  phone: string;
  image: string;
  transmission: string;
  fuel: string;
  seats: number;
  kmIncluded: string;
  options: string[];
  recommended: boolean;
  description: string;
};

export const vehicles: Vehicle[] = [
  // --- 4X4 & SAHARA ---
  {
    id: 1,
    name: "Toyota Land Cruiser Prado",
    type: "4x4",
    agency: "Sahara Expéditions",
    city: "Tamanrasset",
    rating: 4.9,
    reviews: 178,
    price: 14000,
    phone: "+213 29 34 56 78",
    image: "/images/cars/cars_8_toyota_land_cruser_39730462701_jpg.webp",
    transmission: "Automatique",
    fuel: "Diesel",
    seats: 7,
    kmIncluded: "Illimité",
    options: ["4x4 renforcé", "GPS désert", "Kit sécurité", "Climatisation"],
    recommended: true,
    description: "Le véhicule de référence pour les pistes du Hoggar et du Sahara. Robustesse légendaire et autonomie maximale.",
  },
  {
    id: 2,
    name: "Nissan Patrol Desert V8",
    type: "4x4",
    agency: "Tassili Raid Auto",
    city: "Djanet",
    rating: 4.8,
    reviews: 145,
    price: 15500,
    phone: "+213 29 47 12 34",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Essence",
    seats: 7,
    kmIncluded: "Illimité",
    options: ["Suspension rehaussée", "Compresseur d'air", "Plaques de désensablage"],
    recommended: true,
    description: "Confort impérial sur les dunes et puissance tout-terrain pour affronter les paysages lunaires du Tassili N'Ajjer.",
  },
  {
    id: 3,
    name: "Toyota Hilux Double Cabine 4x4",
    type: "Pickup",
    agency: "Saoura Car Rental",
    city: "Ghardaïa",
    rating: 4.7,
    reviews: 120,
    price: 9500,
    phone: "+213 29 88 23 45",
    image: "/images/cars/cars_2_marchand_de_datte_en_pate_avec_sa_t.webp",
    transmission: "Manuelle",
    fuel: "Diesel",
    seats: 5,
    kmIncluded: "300 km/jour",
    options: ["4x4", "Grande benne", "Climatisation renforcée"],
    recommended: false,
    description: "Pickup tout-terrain fiable et polyvalent, idéal pour transporter matériel de bivouac et explorer la vallée du M'Zab.",
  },
  {
    id: 4,
    name: "Range Rover Sahara Edition",
    type: "4x4",
    agency: "Grand Sud Prestige",
    city: "Tamanrasset",
    rating: 4.7,
    reviews: 112,
    price: 16000,
    phone: "+213 29 34 88 90",
    image: "/images/cars/cars_4_gianni_lora_lamia_range_rover_recor.webp",
    transmission: "Automatique",
    fuel: "Diesel",
    seats: 5,
    kmIncluded: "Illimité",
    options: ["4x4 luxe", "Sellerie cuir", "GPS satellite", "Glacière intégrée"],
    recommended: true,
    description: "L'alliance absolue du grand luxe britannique et de l'aventure saharienne pour un voyage inoubliable dans le Sud.",
  },
  {
    id: 5,
    name: "Dacia Duster 4x4 Prestige",
    type: "SUV",
    agency: "Béjaïa Auto Location",
    city: "Béjaïa",
    rating: 4.6,
    reviews: 160,
    price: 6500,
    phone: "+213 34 16 78 90",
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&h=800&fit=crop&q=80",
    transmission: "Manuelle",
    fuel: "Diesel",
    seats: 5,
    kmIncluded: "250 km/jour",
    options: ["Transmission 4x4", "GPS intégré", "Caméra de recul"],
    recommended: false,
    description: "Le baroudeur idéal pour sillonner les corniches de Kabylie, le parc de Gouraya et les routes de montagne côtières.",
  },

  // --- SUVS & MODERN CROSSOVERS ---
  {
    id: 6,
    name: "Hyundai Tucson N-Line",
    type: "SUV",
    agency: "Cirta Car Service",
    city: "Constantine",
    rating: 4.7,
    reviews: 135,
    price: 8500,
    phone: "+213 31 84 12 34",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Diesel",
    seats: 5,
    kmIncluded: "250 km/jour",
    options: ["Toit panoramique", "Écran tactile 10 pouces", "Régulateur adaptatif"],
    recommended: true,
    description: "SUV au design futuriste et très spacieux, parfait pour les trajets entre Constantine, Batna et les Aurès.",
  },
  {
    id: 7,
    name: "Peugeot 3008 GT",
    type: "SUV",
    agency: "AVIS Algérie",
    city: "Alger",
    rating: 4.8,
    reviews: 210,
    price: 9000,
    phone: "+213 21 68 45 67",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "300 km/jour",
    options: ["Cockpit digital", "Aide au stationnement", "Bluetooth", "Sièges massants"],
    recommended: true,
    description: "Conduite dynamique et confort haut de gamme pour vos séjours d'affaires et d'escapades le long de la côte algéroise.",
  },
  {
    id: 8,
    name: "Kia Sportage Allure",
    type: "SUV",
    agency: "Bahia Drive",
    city: "Oran",
    rating: 4.6,
    reviews: 140,
    price: 8000,
    phone: "+213 41 55 23 45",
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "250 km/jour",
    options: ["Climatisation bi-zone", "Caméra 360", "Apple CarPlay & Android Auto"],
    recommended: false,
    description: "Élégant SUV familial pour explorer la corniche oranaise, les plages des Andalouses et le centre historique.",
  },

  // --- BERLINES & AFFAIRES ---
  {
    id: 9,
    name: "Renault Talisman Executive",
    type: "Berline",
    agency: "Europcar Algeria",
    city: "Alger",
    rating: 4.6,
    reviews: 165,
    price: 6500,
    phone: "+213 21 67 89 12",
    image: "/images/cars/cars_6_renault_talisman_jpg.webp",
    transmission: "Automatique",
    fuel: "Diesel",
    seats: 5,
    kmIncluded: "300 km/jour",
    options: ["Châssis 4Control", "GPS Europe/Afrique", "Sellerie cuir", "Régulateur"],
    recommended: false,
    description: "Berline de standing offrant un silence de roulement remarquable et un coffre gigantesque pour les longs trajets autoroutiers.",
  },
  {
    id: 10,
    name: "Toyota Corolla Hybrid",
    type: "Berline",
    agency: "Location Plus Express",
    city: "Alger",
    rating: 4.5,
    reviews: 190,
    price: 5500,
    phone: "+213 21 89 12 34",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Hybride",
    seats: 5,
    kmIncluded: "250 km/jour",
    options: ["Motorisation hybride économe", "Sécurité active", "Boîte e-CVT souple"],
    recommended: false,
    description: "Fiabilité mondiale et consommation de carburant minime, parfaite pour les déplacements urbains et interurbains fluides.",
  },
  {
    id: 11,
    name: "Skoda Octavia Business",
    type: "Berline",
    agency: "Seybouse Location",
    city: "Annaba",
    rating: 4.6,
    reviews: 125,
    price: 6000,
    phone: "+213 38 45 67 89",
    image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Diesel",
    seats: 5,
    kmIncluded: "250 km/jour",
    options: ["Coffre hayon 600L", "Climatisation Climatronic", "Phares LED"],
    recommended: false,
    description: "Grande berline élégante et sobre pour découvrir Annaba, El Kala et les plages turquoise de la côte Est.",
  },
  {
    id: 12,
    name: "Hyundai Accent Berline",
    type: "Berline",
    agency: "Hertz Algérie",
    city: "Constantine",
    rating: 4.4,
    reviews: 110,
    price: 4200,
    phone: "+213 31 45 67 89",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "200 km/jour",
    options: ["Climatisation", "Bluetooth", "Prise USB"],
    recommended: false,
    description: "Berline compacte polyvalente très appréciée en Algérie pour son excellent compromis confort, coffre et budget.",
  },

  // --- CITADINES COMPACTES ---
  {
    id: 13,
    name: "Peugeot 208 GT Line",
    type: "Citadine",
    agency: "AVIS Algérie",
    city: "Oran",
    rating: 4.5,
    reviews: 175,
    price: 4500,
    phone: "+213 41 56 78 90",
    image: "/images/cars/cars_5_peugeot_208_jpg.webp",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "200 km/jour",
    options: ["i-Cockpit 3D", "Écran tactile", "Jantes alliage", "Climatisation"],
    recommended: true,
    description: "Citadine moderne agile et racée. Facile à garer dans les ruelles commerçantes du centre d'Oran.",
  },
  {
    id: 14,
    name: "Renault Clio 5 Intens",
    type: "Citadine",
    agency: "Zianides Car",
    city: "Tlemcen",
    rating: 4.5,
    reviews: 140,
    price: 4300,
    phone: "+213 43 27 89 00",
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&h=800&fit=crop&q=80",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "200 km/jour",
    options: ["Carte mains-libres", "Climatisation auto", "Aide au freinage d'urgence"],
    recommended: false,
    description: "Très confortable et silencieuse sur route, idéale pour explorer la ville d'art de Tlemcen et ses environs verdoyants.",
  },
  {
    id: 15,
    name: "Volkswagen Golf 8 R-Line",
    type: "Citadine",
    agency: "Alger City Drive",
    city: "Alger",
    rating: 4.8,
    reviews: 230,
    price: 7500,
    phone: "+213 21 74 12 34",
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&h=800&fit=crop&q=80",
    transmission: "Automatique",
    fuel: "Diesel",
    seats: 5,
    kmIncluded: "250 km/jour",
    options: ["Boîte DSG7", "Digital Cockpit Pro", "Éclairage Matrix LED", "GPS"],
    recommended: true,
    description: "La compacte d'élite par excellence. Conduite précise, finition soignée et tenue de route irréprochable.",
  },
  {
    id: 16,
    name: "Seat Ibiza FR",
    type: "Citadine",
    agency: "West Coast Cars",
    city: "Oran",
    rating: 4.4,
    reviews: 98,
    price: 4200,
    phone: "+213 41 33 45 67",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&h=800&fit=crop&q=80",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "200 km/jour",
    options: ["Pack Sport FR", "Phares Full LED", "Système audio haute fidélité"],
    recommended: false,
    description: "Look jeune et dynamique, idéale pour les escapades en bord de mer le long du littoral oranais.",
  },

  // --- VINTAGE & VÉHICULES DE COLLECTION ---
  {
    id: 17,
    name: "Peugeot 504 Berline",
    type: "Classique",
    agency: "Classic Cars Algérie",
    city: "Constantine",
    rating: 4.6,
    reviews: 88,
    price: 3500,
    phone: "+213 31 92 45 67",
    image: "/images/cars/cars_1_marchand_embulant_de_tapis_avec_sa_.webp",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "150 km/jour",
    options: ["Véhicule mythique restauré", "Intérieur d'origine soigné", "Chauffeur disponible sur demande"],
    recommended: true,
    description: "L'icône automobile incontournable d'Algérie. Traverser les ponts de Constantine à bord d'une 504 est une expérience inoubliable.",
  },
  {
    id: 18,
    name: "Citroën DS Pallas 1972",
    type: "Classique",
    agency: "Heritage Prestige Cars",
    city: "Alger",
    rating: 4.9,
    reviews: 72,
    price: 6000,
    phone: "+213 21 75 23 45",
    image: "/images/cars/cars_3_citroen_collection_jpg.webp",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "120 km/jour",
    options: ["Suspension hydropneumatique", "Véhicule de cérémonie / tournage", "État concours"],
    recommended: true,
    description: "La reine de la route. Suspension au confort ouaté incomparable pour une visite royale de la capitale.",
  },
  {
    id: 19,
    name: "Renault 8 Gordini 1300",
    type: "Classique",
    agency: "Heritage Cars Oran",
    city: "Oran",
    rating: 4.7,
    reviews: 64,
    price: 4500,
    phone: "+213 41 45 67 89",
    image: "/images/cars/cars_12_renault_8_gordini_24797841987_jpg.webp",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 4,
    kmIncluded: "100 km/jour",
    options: ["Bande blanche historique", "Moteur Gordini restauré", "Sensations vintage"],
    recommended: false,
    description: "Une légende vivante du rallye et de la passion automobile. Sensations pures et nostalgie des circuits.",
  },
  {
    id: 20,
    name: "Renault 4CV Vintage",
    type: "Classique",
    agency: "Heritage Cars",
    city: "Alger",
    rating: 4.4,
    reviews: 45,
    price: 3000,
    phone: "+213 21 75 23 45",
    image: "/images/cars/cars_7_renault_4cv_commerciale_7915714548_.webp",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 4,
    kmIncluded: "100 km/jour",
    options: ["Véhicule historique", "Idéal photos rétro"],
    recommended: false,
    description: "Petite et attachante, la 4CV vous fait redécouvrir Alger à un rythme paisible et empreint de poésie.",
  },
  {
    id: 21,
    name: "Renault 16 TL Tourisme",
    type: "Classique",
    agency: "Heritage Cars",
    city: "Alger",
    rating: 4.3,
    reviews: 38,
    price: 3200,
    phone: "+213 21 75 23 45",
    image: "/images/cars/cars_10_renault_16_38960104884_jpg.webp",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 5,
    kmIncluded: "120 km/jour",
    options: ["Grand hayon modulable", "Sièges moelleux", "Confort vintage"],
    recommended: false,
    description: "Pionnière du confort moderne avec son grand hayon pratique et sa suspension ultra-souple.",
  },
  {
    id: 22,
    name: "Renault Rodeo Plein Air",
    type: "Classique",
    agency: "Heritage Cars Oran",
    city: "Oran",
    rating: 4.2,
    reviews: 31,
    price: 2800,
    phone: "+213 41 45 67 89",
    image: "/images/cars/cars_9_renault_rodeo_39021163724_jpg.webp",
    transmission: "Manuelle",
    fuel: "Essence",
    seats: 4,
    kmIncluded: "100 km/jour",
    options: ["Capote amovible", "Conduite cheveux au vent", "Look baroudeur vintage"],
    recommended: false,
    description: "Le cabriolet utilitaire vintage le plus amusant pour longer les plages de la côte ouest sous le soleil.",
  },
];

export const vehicleCities = [
  "All",
  "Alger",
  "Oran",
  "Constantine",
  "Annaba",
  "Tlemcen",
  "Béjaïa",
  "Ghardaïa",
  "Tamanrasset",
  "Djanet",
];

export const vehicleTypes = [
  "All",
  "4x4",
  "SUV",
  "Berline",
  "Citadine",
  "Pickup",
  "Classique",
];
