export type Restaurant = {
  id: number;
  name: string;
  city: string;
  cuisine: string;
  priceRange: string;
  priceAvg?: number;
  rating: number;
  reviews: number;
  halal: boolean;
  terrace: boolean;
  phone: string;
  specialties: string[];
  description: string;
  image: string;
  highlights?: string[];
};

export const restaurants: Restaurant[] = [
  // --- ALGER ---
  {
    id: 1,
    name: "Restaurant El Jenina",
    city: "Alger",
    cuisine: "Gastronomique",
    priceRange: "3 000 - 5 000 DA",
    priceAvg: 3800,
    rating: 4.8,
    reviews: 340,
    halal: true,
    terrace: false,
    phone: "+213 21 74 25 25",
    specialties: ["Rechta algéroise", "Tajine El Bey", "Shorba Frik", "M'touwem"],
    description: "Temple de la haute gastronomie algéroise dans le quartier Sacré-Cœur. Cadre hispano-mauresque feutré et recettes ancestrales exécutées à la perfection.",
    image: "/images/restaurants/restaurants_1_alger-restaurant-etoile_1940_jpg.webp",
    highlights: ["Maison de maître", "Rechta artisanale", "Service d'exception", "Ambiance feutrée"],
  },
  {
    id: 2,
    name: "Le Petit Rocher",
    city: "Alger",
    cuisine: "Poissons & Fruits de mer",
    priceRange: "3 500 - 6 000 DA",
    priceAvg: 4500,
    rating: 4.7,
    reviews: 285,
    halal: true,
    terrace: true,
    phone: "+213 23 20 15 15",
    specialties: ["Loup de mer grillé", "Crevettes royales", "Espadon", "Bouillabaisse"],
    description: "Posé au bord des vagues à Aïn Bénian avec vue panoramique sur la Méditerranée. Arrivage quotidien de poissons sauvages du large.",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=1200&h=800&fit=crop&q=80",
    highlights: ["Vue panoramique mer", "Terrasse marine", "Pêche du jour", "Cadre romantique"],
  },
  {
    id: 3,
    name: "La Pagode Phénicienne",
    city: "Alger",
    cuisine: "Poissons & Fruits de mer",
    priceRange: "2 500 - 4 500 DA",
    priceAvg: 3200,
    rating: 4.6,
    reviews: 210,
    halal: true,
    terrace: true,
    phone: "+213 21 71 88 90",
    specialties: ["Dorade royale au gros sel", "Friture de rougets", "Calamars farcis"],
    description: "Institution du port d'Alger offrant une terrasse spectaculaire face aux navires et à la baie illuminée.",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1200&h=800&fit=crop&q=80",
    highlights: ["Front de mer", "Poissons au feu de bois", "Terrasse d'été", "Vue port d'Alger"],
  },
  {
    id: 4,
    name: "Dar El Beida Couscousserie",
    city: "Alger",
    cuisine: "Traditionnelle",
    priceRange: "1 500 - 2 800 DA",
    priceAvg: 2000,
    rating: 4.5,
    reviews: 195,
    halal: true,
    terrace: false,
    phone: "+213 21 50 12 34",
    specialties: ["Couscous Royal aux sept légumes", "Chorba bayda", "Bourek au poulet"],
    description: "Ambiance chaleureuse et généreuse autour du couscous roulé à la main et cuit à la vapeur traditionnelle.",
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=1200&h=800&fit=crop&q=80",
    highlights: ["Couscous roulé main", "Portions généreuses", "Ambiance familiale", "Pâtisseries au miel"],
  },
  {
    id: 5,
    name: "Restaurant Abu Karam",
    city: "Alger",
    cuisine: "Moyen-Orientale",
    priceRange: "2 000 - 3 500 DA",
    priceAvg: 2600,
    rating: 4.4,
    reviews: 160,
    halal: true,
    terrace: true,
    phone: "+213 21 74 56 78",
    specialties: ["Grillades mixtes", "Mezzés froids et chauds", "Shawarma d'agneau"],
    description: "Saveurs du Levant au cœur de la capitale avec pains chauds cuits minute et mezzés raffinés.",
    image: "/images/restaurants/restaurants_15__jpg.webp",
    highlights: ["Mezzés variés", "Pain au four à bois", "Terrasse animée", "Thé à la menthe offert"],
  },

  // --- ORAN ---
  {
    id: 6,
    name: "Le Méditerranéen",
    city: "Oran",
    cuisine: "Méditerranéenne",
    priceRange: "2 500 - 4 500 DA",
    priceAvg: 3400,
    rating: 4.8,
    reviews: 310,
    halal: true,
    terrace: true,
    phone: "+213 41 40 88 00",
    specialties: ["Paella oranaise", "Gambas poêlées à l'ail", "Calamars à la plancha"],
    description: "Sur le prestigieux front de mer d'Oran, un hommage gourmand aux liens maritimes entre l'Oranie et l'Andalousie.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=800&fit=crop&q=80",
    highlights: ["Vue baie d'Oran", "Paella aux fruits de mer", "Terrasse panoramique", "Ambiance hispano-oranaise"],
  },
  {
    id: 7,
    name: "Restaurant Le Corsaire",
    city: "Oran",
    cuisine: "Poissons & Fruits de mer",
    priceRange: "2 000 - 3 800 DA",
    priceAvg: 2800,
    rating: 4.7,
    reviews: 245,
    halal: true,
    terrace: true,
    phone: "+213 41 39 44 22",
    specialties: ["Sardinades grillées", "Espadon mariné", "Salade oranaise de poulpe"],
    description: "Au port de la Pêcherie sous la forteresse de Santa Cruz. Poissons ultra-frais grillés devant vos yeux.",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=1200&h=800&fit=crop&q=80",
    highlights: ["Pêcherie d'Oran", "Vue sur Santa Cruz", "Sardines fraîches", "Accueil chaleureux"],
  },
  {
    id: 8,
    name: "Dar El Kaid",
    city: "Oran",
    cuisine: "Traditionnelle",
    priceRange: "2 500 - 4 000 DA",
    priceAvg: 3000,
    rating: 4.6,
    reviews: 180,
    halal: true,
    terrace: false,
    phone: "+213 41 33 12 34",
    specialties: ["Mechoui à l'ancienne", "Couscous de l'Ouest", "Tajine de veau aux pruneaux"],
    description: "Demeure d'inspiration marocaine et andalouse où les viandes cuites au four d'argile fondent sous la dent.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&h=800&fit=crop&q=80",
    highlights: ["Mechoui fondant", "Décor oriental boisé", "Cuisine généreuse", "Salons privés"],
  },
  {
    id: 9,
    name: "La Comète",
    city: "Oran",
    cuisine: "Gastronomique",
    priceRange: "3 000 - 5 500 DA",
    priceAvg: 4000,
    rating: 4.5,
    reviews: 165,
    halal: true,
    terrace: true,
    phone: "+213 41 29 55 66",
    specialties: ["Filet de bœuf aux morilles", "Soupe de poissons de roche", "Crème brûlée"],
    description: "Brasserie historique de la ville d'Oran depuis 1930, lieu de rencontre privilégié des artistes et lettrés.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=800&fit=crop&q=80",
    highlights: ["Brasserie historique 1930", "Service en livrée", "Cave d'exception", "Centre-ville"],
  },

  // --- CONSTANTINE ---
  {
    id: 10,
    name: "Restaurant Cirta Gourmet",
    city: "Constantine",
    cuisine: "Gastronomique",
    priceRange: "2 800 - 4 500 DA",
    priceAvg: 3500,
    rating: 4.9,
    reviews: 290,
    halal: true,
    terrace: true,
    phone: "+213 31 92 70 00",
    specialties: ["Chakhchoukha constantinoise", "Trida au poulet fermier", "Djouzia au miel d'acacia", "Tajine El Ain"],
    description: "Le summum du raffinement gastronomique constantinois. Chaque plat célèbre les siècles d'histoire de la cité numide.",
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=1200&h=800&fit=crop&q=80",
    highlights: ["Chakhchoukha de fête", "Véritable Djouzia maison", "Cadre d'époque", "Vue sur les gorges"],
  },
  {
    id: 11,
    name: "El Bahia des Ponts",
    city: "Constantine",
    cuisine: "Traditionnelle",
    priceRange: "1 800 - 3 200 DA",
    priceAvg: 2400,
    rating: 4.7,
    reviews: 220,
    halal: true,
    terrace: true,
    phone: "+213 31 84 55 12",
    specialties: ["Kefta bel bsal", "Chorba frik constantinoise", "Berkoukes aux légumes"],
    description: "Terrasse vertigineuse surplombant le canyon du Rhummel et le pont suspendu Sidi M'Cid.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=800&fit=crop&q=80",
    highlights: ["Vue panoramique canyon", "Terrasse suspendue", "Saveurs du terroir", "Coucher de soleil"],
  },
  {
    id: 12,
    name: "Dar Diaf Constantine",
    city: "Constantine",
    cuisine: "Traditionnelle",
    priceRange: "2 000 - 3 500 DA",
    priceAvg: 2600,
    rating: 4.5,
    reviews: 140,
    halal: true,
    terrace: false,
    phone: "+213 31 81 22 44",
    specialties: ["Couscous aux cardons", "Mhalbi à l'eau de rose", "Bourek annabi"],
    description: "Hospitalité généreuse de l'Est algérien dans un décor orné de dinanderie martelée et de boiseries sculptées.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=800&fit=crop&q=80",
    highlights: ["Artisanat constantinois", "Accueil chaleureux", "Desserts traditionnels", "Repas de fête"],
  },

  // --- TLEMCEN ---
  {
    id: 13,
    name: "Restaurant Panoramique Lalla Setti",
    city: "Tlemcen",
    cuisine: "Gastronomique",
    priceRange: "2 800 - 4 800 DA",
    priceAvg: 3600,
    rating: 4.8,
    reviews: 260,
    halal: true,
    terrace: true,
    phone: "+213 43 40 22 33",
    specialties: ["Pastilla tlemcénienne au pigeon", "Couscous zianide aux raisins secs", "Halwat El Ksa"],
    description: "Perché sur le plateau de Lalla Setti avec vue féerique sur toute la ville de Tlemcen et ses minarets historiques.",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1200&h=800&fit=crop&q=80",
    highlights: ["Vue panoramique plateau", "Pastilla croustillante", "Grand parc boisé", "Cuisine princière zianide"],
  },
  {
    id: 14,
    name: "Le Riad du Mechouar",
    city: "Tlemcen",
    cuisine: "Traditionnelle",
    priceRange: "2 000 - 3 500 DA",
    priceAvg: 2700,
    rating: 4.6,
    reviews: 175,
    halal: true,
    terrace: true,
    phone: "+213 43 27 15 15",
    specialties: ["Tajine d'agneau aux amandes", "Hrira tlemcénienne", "Ghoriba aux noisettes"],
    description: "Niché dans les ruelles entourant le Palais Royal El Mechouar. Patio ombragé avec fontaine zellige et thé à la menthe.",
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=1200&h=800&fit=crop&q=80",
    highlights: ["Patio zellige & fontaine", "Proche Palais El Mechouar", "Hrira authentique", "Ambiance andalouse"],
  },

  // --- ANNABA ---
  {
    id: 15,
    name: "La Caravelle Chapuis",
    city: "Annaba",
    cuisine: "Poissons & Fruits de mer",
    priceRange: "3 000 - 5 500 DA",
    priceAvg: 3900,
    rating: 4.8,
    reviews: 320,
    halal: true,
    terrace: true,
    phone: "+213 38 88 20 20",
    specialties: ["Véritable Brik d'Annaba à l'œuf coulant", "Langoustes grillées", "Riz aux fruits de mer"],
    description: "Adresse incontournable sur la corniche de Chapuis face au golfe. Réputée pour ses briks croustillantes et ses crustacés d'exception.",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=1200&h=800&fit=crop&q=80",
    highlights: ["Brik d'Annaba n°1", "Terrasse plage Chapuis", "Langoustes fraîches", "Vue mer azur"],
  },
  {
    id: 16,
    name: "Restaurant La Baie d'Annaba",
    city: "Annaba",
    cuisine: "Méditerranéenne",
    priceRange: "2 200 - 3 800 DA",
    priceAvg: 2900,
    rating: 4.5,
    reviews: 185,
    halal: true,
    terrace: true,
    phone: "+213 38 45 11 22",
    specialties: ["Grillades au feu de bois", "Calamars sautés persillade", "Salade méchouia"],
    description: "Ambiance décontractée les pieds dans le sable au belvédère d'Annaba pour de savoureux repas en famille.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=800&fit=crop&q=80",
    highlights: ["Pieds dans l'eau", "Grillades savoureuses", "Terrasse marine", "Idéal familles"],
  },

  // --- BÉJAÏA ---
  {
    id: 17,
    name: "La Brise de Mer",
    city: "Béjaïa",
    cuisine: "Poissons & Fruits de mer",
    priceRange: "2 500 - 4 200 DA",
    priceAvg: 3200,
    rating: 4.7,
    reviews: 240,
    halal: true,
    terrace: true,
    phone: "+213 34 20 33 44",
    specialties: ["Espadon grillé", "Friture de merlan", "Salade kabyle à l'huile d'olive de terroir"],
    description: "Face au port de plaisance de Béjaïa avec vue sur le Cap Carbon. Cuisine marine arrosée des meilleures huiles d'olive kabyles.",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=1200&h=800&fit=crop&q=80",
    highlights: ["Huile d'olive médaillée", "Vue Cap Carbon", "Arrivage journalier", "Terrasse portuaire"],
  },
  {
    id: 18,
    name: "Auberge du Gouraya",
    city: "Béjaïa",
    cuisine: "Traditionnelle",
    priceRange: "1 800 - 3 000 DA",
    priceAvg: 2300,
    rating: 4.6,
    reviews: 170,
    halal: true,
    terrace: true,
    phone: "+213 34 16 45 12",
    specialties: ["Tikourbabine (boulettes kabyles en sauce)", "Couscous à l'orge et glands", "Aghrum au feu de bois"],
    description: "Au cœur du parc national de Gouraya, immersion authentique dans les saveurs de montagne kabyles.",
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=1200&h=800&fit=crop&q=80",
    highlights: ["Plats traditionnels kabyles", "Parc de Gouraya", "Air pur de montagne", "Galettes cuites au feu"],
  },

  // --- TIPAZA ---
  {
    id: 19,
    name: "La Baie des Poissons",
    city: "Tipaza",
    cuisine: "Poissons & Fruits de mer",
    priceRange: "2 400 - 4 000 DA",
    priceAvg: 3100,
    rating: 4.7,
    reviews: 215,
    halal: true,
    terrace: true,
    phone: "+213 24 43 18 18",
    specialties: ["Loup de mer rôti aux herbes", "Rougets de roche", "Crevettes sautées"],
    description: "Juste à côté des ruines romaines classées UNESCO et du petit port de pêche de Tipaza. Cadre idyllique au bord de l'eau.",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1200&h=800&fit=crop&q=80",
    highlights: ["Face aux ruines romaines", "Poissons de roche ultra-frais", "Terrasse marine", "Coucher de soleil magique"],
  },

  // --- GHARDAÏA & SAHARA ---
  {
    id: 20,
    name: "Maison Mozabite",
    city: "Ghardaïa",
    cuisine: "Saharienne",
    priceRange: "1 800 - 3 200 DA",
    priceAvg: 2400,
    rating: 4.9,
    reviews: 195,
    halal: true,
    terrace: true,
    phone: "+213 29 88 50 50",
    specialties: ["Couscous du M'Zab aux herbes du désert", "Tajine de dattes & dromadaire", "Thé saharien mousseux"],
    description: "Au ksar préservé de Beni Isguen. Dîners aux lanternes sous la palmeraie avec dégustation de dattes fraîches et thé cuit sur la braise.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&h=800&fit=crop&q=80",
    highlights: ["Palmeraie UNESCO", "Cuisine saharienne rare", "Cérémonie du thé", "Cadre paisible"],
  },
  {
    id: 21,
    name: "Bivouac des Dunes Taghit",
    city: "Taghit",
    cuisine: "Saharienne",
    priceRange: "2 000 - 3 500 DA",
    priceAvg: 2600,
    rating: 4.8,
    reviews: 180,
    halal: true,
    terrace: true,
    phone: "+213 49 76 22 11",
    specialties: ["Taguella (pain traditionnel cuit sous le sable)", "Mechoui saharien au feu de bois", "Thé à la menthe nomade"],
    description: "Déguster un repas saharien traditionnel au pied de la gigantesque dune rouge de Taghit, sous la voûte céleste du désert.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=800&fit=crop&q=80",
    highlights: ["Taguella ancestrale", "Feu de camp sous les étoiles", "Grande dune de Taghit", "Musique nomade"],
  },
  {
    id: 22,
    name: "Restaurant Palmeraie de Biskra",
    city: "Biskra",
    cuisine: "Traditionnelle",
    priceRange: "1 500 - 2 500 DA",
    priceAvg: 1900,
    rating: 4.5,
    reviews: 130,
    halal: true,
    terrace: true,
    phone: "+213 33 74 15 20",
    specialties: ["Doubara biskrie aux fèves et pois chiches", "Chakhchoukha de Biskra", "Dattes Deglet Nour tièdes"],
    description: "La capitale des Zibans vous accueille pour savourer la célèbre Doubara épicée à l'huile d'olive et au piment, spécialité emblématique.",
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=1200&h=800&fit=crop&q=80",
    highlights: ["Doubara originale", "Dattes fraîches de la palmeraie", "Saveurs épicées", "Tarif très accessible"],
  },
];

export const restaurantCities = [
  "All",
  "Alger",
  "Oran",
  "Constantine",
  "Tlemcen",
  "Annaba",
  "Béjaïa",
  "Tipaza",
  "Ghardaïa",
  "Taghit",
  "Biskra",
];

export const restaurantCuisines = [
  "All",
  "Traditionnelle",
  "Poissons & Fruits de mer",
  "Méditerranéenne",
  "Saharienne",
  "Gastronomique",
  "Moyen-Orientale",
];
