export type TransportRoute = {
  id: number;
  type: "train" | "bus" | "flight" | "ferry";
  operator: string;
  from: string;
  to: string;
  departure: string;
  arrival: string;
  duration: string;
  price: number;
  available: boolean;
  frequency: string;
  classType: string;
  description: string;
};

export const transportRoutes: TransportRoute[] = [
  // --- TRAINS (SNTF CORADIA & GRANDES LIGNES) ---
  {
    id: 1,
    type: "train",
    operator: "SNTF Coradia",
    from: "Alger",
    to: "Oran",
    departure: "08:00",
    arrival: "12:15",
    duration: "4h 15m",
    price: 2500,
    available: true,
    frequency: "Quotidien (3 départs/jour)",
    classType: "1ère classe climatisée",
    description: "Train grande vitesse Coradia reliant les deux plus grandes métropoles algériennes le long de la plaine de la Mitidja et du Chélif.",
  },
  {
    id: 2,
    type: "train",
    operator: "SNTF Coradia",
    from: "Alger",
    to: "Constantine",
    departure: "07:30",
    arrival: "13:30",
    duration: "6h 00m",
    price: 2800,
    available: true,
    frequency: "Quotidien",
    classType: "1ère classe climatisée",
    description: "Liaison ferroviaire moderne traversant les spectaculaires gorges des Portes de Fer et les hauts plateaux de Sétif.",
  },
  {
    id: 3,
    type: "train",
    operator: "SNTF Nuit Express",
    from: "Alger",
    to: "Annaba",
    departure: "21:30",
    arrival: "06:30",
    duration: "9h 00m",
    price: 3200,
    available: true,
    frequency: "Tous les soirs",
    classType: "Cabine couchette confort",
    description: "Train de nuit tout confort pour se réveiller au petit matin sur la côte turquoise d'Annaba.",
  },
  {
    id: 4,
    type: "train",
    operator: "SNTF Autorail",
    from: "Oran",
    to: "Tlemcen",
    departure: "09:15",
    arrival: "11:15",
    duration: "2h 00m",
    price: 850,
    available: true,
    frequency: "Quotidien (4 départs)",
    classType: "Classe Confort",
    description: "Navette rapide et confortable entre la capitale de l'Oranie et la cité d'art zianide de Tlemcen.",
  },
  {
    id: 5,
    type: "train",
    operator: "SNTF Autorail",
    from: "Constantine",
    to: "Biskra",
    departure: "06:45",
    arrival: "10:15",
    duration: "3h 30m",
    price: 1200,
    available: true,
    frequency: "Quotidien",
    classType: "Classe Confort",
    description: "Descente spectaculaire depuis les ponts de Constantine à travers les gorges d'El Kantara jusqu'aux palmeraies de Biskra.",
  },
  {
    id: 6,
    type: "train",
    operator: "SNTF Saharien",
    from: "Oran",
    to: "Béchar",
    departure: "20:00",
    arrival: "06:00",
    duration: "10h 00m",
    price: 2400,
    available: true,
    frequency: "Quotidien",
    classType: "Couchette climatisée",
    description: "La grande ligne transsaharienne reliant la Méditerranée aux portes du Grand Erg Occidental et de la Saoura.",
  },
  {
    id: 7,
    type: "train",
    operator: "SNTF Coradia",
    from: "Alger",
    to: "Béjaïa",
    departure: "06:00",
    arrival: "10:00",
    duration: "4h 00m",
    price: 1500,
    available: true,
    frequency: "Quotidien",
    classType: "1ère classe",
    description: "Voyage pittoresque longeant les contreforts de la Kabylie maritime jusqu'au golfe de Bougie.",
  },

  // --- VOLS INTÉRIEURS (AIR ALGÉRIE & TASSILI AIRLINES) ---
  {
    id: 8,
    type: "flight",
    operator: "Air Algérie",
    from: "Alger",
    to: "Tamanrasset",
    departure: "14:00",
    arrival: "16:30",
    duration: "2h 30m",
    price: 13500,
    available: true,
    frequency: "Tous les jours",
    classType: "Classe Économique (Boeing 737)",
    description: "Survol direct du Grand Sud algérien vers le cœur du massif du Hoggar. Collation et bagage 20kg inclus.",
  },
  {
    id: 9,
    type: "flight",
    operator: "Air Algérie",
    from: "Alger",
    to: "Djanet",
    departure: "22:30",
    arrival: "00:45",
    duration: "2h 15m",
    price: 14000,
    available: true,
    frequency: "4 fois / semaine",
    classType: "Classe Économique (Boeing 737)",
    description: "Vol direct vers l'oasis féerique de Djanet et les merveilles du Parc National du Tassili N'Ajjer.",
  },
  {
    id: 10,
    type: "flight",
    operator: "Air Algérie",
    from: "Alger",
    to: "Oran",
    departure: "08:30",
    arrival: "09:30",
    duration: "1h 00m",
    price: 7500,
    available: true,
    frequency: "5 vols / jour",
    classType: "Classe Économique",
    description: "Navette aérienne express reliant l'aéroport Houari Boumediene d'Alger à l'aéroport Ahmed Ben Bella d'Oran.",
  },
  {
    id: 11,
    type: "flight",
    operator: "Air Algérie",
    from: "Alger",
    to: "Constantine",
    departure: "11:00",
    arrival: "11:55",
    duration: "0h 55m",
    price: 7000,
    available: true,
    frequency: "4 vols / jour",
    classType: "Classe Économique",
    description: "Liaison aérienne rapide vers l'aéroport Mohamed Boudiaf de Constantine pour vos rendez-vous dans l'Est.",
  },
  {
    id: 12,
    type: "flight",
    operator: "Air Algérie",
    from: "Alger",
    to: "Annaba",
    departure: "16:00",
    arrival: "17:00",
    duration: "1h 00m",
    price: 7200,
    available: true,
    frequency: "3 vols / jour",
    classType: "Classe Économique",
    description: "Vol direct reliant la capitale à la cité d'Hippone et à la côte est algérienne.",
  },
  {
    id: 13,
    type: "flight",
    operator: "Tassili Airlines",
    from: "Alger",
    to: "Ghardaïa",
    departure: "09:00",
    arrival: "10:15",
    duration: "1h 15m",
    price: 8500,
    available: true,
    frequency: "3 fois / semaine",
    classType: "Bombardier Q400",
    description: "Escapade rapide vers la vallée classée UNESCO du M'Zab à bord des appareils modernes de Tassili Airlines.",
  },
  {
    id: 14,
    type: "flight",
    operator: "Air Algérie",
    from: "Alger",
    to: "Timimoun",
    departure: "13:15",
    arrival: "14:55",
    duration: "1h 40m",
    price: 9800,
    available: true,
    frequency: "Bi-hebdomadaire",
    classType: "Classe Économique",
    description: "Atterrissez au cœur de l'oasis rouge de Timimoun sans fatigue pour entamer votre séjour saharien.",
  },
  {
    id: 15,
    type: "flight",
    operator: "Air Algérie",
    from: "Alger",
    to: "Biskra",
    departure: "17:30",
    arrival: "18:40",
    duration: "1h 10m",
    price: 7800,
    available: true,
    frequency: "Quotidien",
    classType: "ATR 72-600",
    description: "Liaison confortable vers la porte du désert et les palmeraies des Zibans.",
  },

  // --- AUTOCARS VIP & INTERURBAINS (SOGRAL / ETUSA) ---
  {
    id: 16,
    type: "bus",
    operator: "SOGRAL VIP Express",
    from: "Alger",
    to: "Tlemcen",
    departure: "07:00",
    arrival: "13:30",
    duration: "6h 30m",
    price: 1800,
    available: true,
    frequency: "3 départs / jour",
    classType: "Bus VIP (Wifi & prises)",
    description: "Autocar grand confort avec sièges inclinables en cuir, climatisation et vidéo à bord sur l'autoroute Est-Ouest.",
  },
  {
    id: 17,
    type: "bus",
    operator: "SOGRAL Grand Sud",
    from: "Alger",
    to: "Ghardaïa",
    departure: "20:00",
    arrival: "05:00",
    duration: "9h 00m",
    price: 2200,
    available: true,
    frequency: "Tous les soirs",
    classType: "Autocar de nuit Premium",
    description: "Trajet nocturne reposant à travers la steppe de Djelfa et les plateaux présahariens.",
  },
  {
    id: 18,
    type: "bus",
    operator: "Trans-Aurès",
    from: "Alger",
    to: "Batna",
    departure: "08:00",
    arrival: "13:30",
    duration: "5h 30m",
    price: 1600,
    available: true,
    frequency: "Quotidien",
    classType: "Confort Climatisé",
    description: "Liaison directe vers la capitale des Aurès, point de départ idéal pour Timgad et le canyon du Ghoufi.",
  },
  {
    id: 19,
    type: "bus",
    operator: "ETUSA Navette",
    from: "Oran",
    to: "Tlemcen",
    departure: "08:00",
    arrival: "10:15",
    duration: "2h 15m",
    price: 600,
    available: true,
    frequency: "Toutes les heures",
    classType: "Autocar Interurbain",
    description: "Départs très fréquents depuis la gare routière El Bahia d'Oran vers la gare de Tlemcen.",
  },
  {
    id: 20,
    type: "bus",
    operator: "Seybouse Express",
    from: "Constantine",
    to: "Annaba",
    departure: "09:00",
    arrival: "11:00",
    duration: "2h 00m",
    price: 700,
    available: true,
    frequency: "Toutes les 45 min",
    classType: "Navette Express",
    description: "Connexion rapide entre les deux pôles métropolitains de l'Est algérien sur autoroute.",
  },
  {
    id: 21,
    type: "bus",
    operator: "Sahel Tourisme",
    from: "Alger",
    to: "Tipaza",
    departure: "08:30",
    arrival: "09:30",
    duration: "1h 00m",
    price: 400,
    available: true,
    frequency: "Toutes les 30 min",
    classType: "Autocar Côtier",
    description: "Navette côtière le long du littoral ouest algérois jusqu'au port antique et aux ruines de Tipaza.",
  },

  // --- FERRIES MARITIMES (ALGÉRIE FERRIES & NOURIS) ---
  {
    id: 22,
    type: "ferry",
    operator: "Algérie Ferries",
    from: "Alger",
    to: "Marseille",
    departure: "12:00",
    arrival: "08:00 +1",
    duration: "20h 00m",
    price: 24000,
    available: true,
    frequency: "3 traversées / semaine",
    classType: "Cabine privée 2 personnes",
    description: "Traversée de la Méditerranée à bord du car-ferry nouvelle génération 'Badji Mokhtar III' avec restaurants et boutiques.",
  },
  {
    id: 23,
    type: "ferry",
    operator: "Algérie Ferries",
    from: "Oran",
    to: "Alicante",
    departure: "19:00",
    arrival: "06:30 +1",
    duration: "11h 30m",
    price: 22000,
    available: true,
    frequency: "3 traversées / semaine",
    classType: "Cabine confort",
    description: "Liaison maritime directe entre la côte oranaise et la péninsule ibérique avec transport de véhicule.",
  },
  {
    id: 24,
    type: "ferry",
    operator: "Algérie Ferries",
    from: "Annaba",
    to: "Marseille",
    departure: "14:00",
    arrival: "10:00 +1",
    duration: "20h 00m",
    price: 25000,
    available: true,
    frequency: "Hebdomadaire",
    classType: "Fauteuil pullman & Cabine",
    description: "Départ grandiose depuis le port d'Annaba face à la basilique Saint-Augustin.",
  },
  {
    id: 25,
    type: "ferry",
    operator: "Nouris Elbahr Ferries",
    from: "Béjaïa",
    to: "Marseille",
    departure: "15:00",
    arrival: "09:00 +1",
    duration: "18h 00m",
    price: 23500,
    available: true,
    frequency: "Bi-hebdomadaire",
    classType: "Cabine couchette",
    description: "Traversée maritime confortable desservant la Kabylie maritime vers le sud de la France.",
  },
];

export const transportTypes = [
  { id: "all", label: "Tous les modes" },
  { id: "train", label: "Train (SNTF)" },
  { id: "flight", label: "Vol (Air Algérie)" },
  { id: "bus", label: "Bus & Autocar" },
  { id: "ferry", label: "Ferry Maritime" },
];

export const transportCities = [
  "All",
  "Alger",
  "Oran",
  "Constantine",
  "Annaba",
  "Tlemcen",
  "Béjaïa",
  "Batna",
  "Ghardaïa",
  "Djanet",
  "Tamanrasset",
  "Timimoun",
  "Biskra",
  "Béchar",
  "Tipaza",
  "Marseille",
  "Alicante",
];
